### ISSUE TITLE
errorMsg 403

### ISSUE THREAD

**Issue by tedmax100** [minus5/go-uof-sdk#3]
conn.Dial, inner: Exception (403) Reason: "username or password not allowed"

I used vaild token and bookmarkerID,but receive this error 
how to fix it ?

**Comment by ianic** [comment]
Try the replay example:

```
export UOF_BOOKMAKER_ID=...
export UOF_TOKEN=...
cd go-uof-sdk/cmd/replay
go build 
./replay -event=12055466
```

That should save all the received messages into ./tmp folder.

**Comment by tedmax100** [comment]
> Try the replay example:
> 
> ```
> export UOF_BOOKMAKER_ID=...
> export UOF_TOKEN=...
> cd go-uof-sdk/cmd/replay
> go build 
> ./replay -event=12055466
> ```
> 
> That should save all the received messages into ./tmp folder.

Thanks Ianic. It was worked.
